[package]
name = "pingora-proxy-demo"
version = "0.1.0"
edition = "2021"
authors = ["Pingora Demo <demo@example.com>"]
description = "A high-performance reverse proxy demo using Pingora"
license = "Apache-2.0"
repository = "https://github.com/example/pingora-proxy-demo"

[dependencies]
pingora-core = "0.6"
pingora-proxy = "0.6"
pingora-http = "0.6"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "1.0"
async-trait = "0.1"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tokio-test = "0.4"
proptest = "1.4"
wiremock = "0.6"
serial_test = "3.0"

[build-dependencies]

[[bench]]
name = "proxy_benchmarks"
harness = false

[[bin]]
name = "proxy-server"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.bench]
debug = true
