[package]
name = "simple-cuda-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["rt", "macros"] }
cudarc = { version = "0.11", features = ["cuda-12-0"] }

[dev-dependencies]
approx = "0.5"