[build]
rustflags = ["-C", "target-cpu=native"]
# Shared target directory in principal worktree for all worktrees
target-dir = "../../inferno/target"
# Uncomment to enable sccache for distributed compilation caching
# rustc-wrapper = "sccache"

[alias]
lint = "clippy --all-targets --all-features -- -D warnings"
fmt-check = "fmt -- --check"
check-all = "check --all-targets --all-features"
test-all = "test --all-features"
coverage = "llvm-cov --all-features --workspace --summary-only --output-path coverage.txt"
