[build]
rustflags = ["-C", "target-cpu=native"]

[alias]
lint = "clippy --all-targets --all-features -- -D warnings"
fmt-check = "fmt -- --check"
check-all = "check --all-targets --all-features"
test-all = "test --all-features"
