name: Benchmark
permissions:
  contents: write
on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  workflow_dispatch:
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install cargo-criterion
        run: cargo install cargo-criterion
      - name: Run benchmarks and check for regressions
        run: ./benchmarking/check-performance.sh
      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-report
          path: |
            benchmark.json
      - name: Commit benchmark results to feature branch
        if: github.event_name == 'pull_request'
        uses: EndBug/add-and-commit@v9
        with:
          add: '.prior_bench'
          message: 'Update benchmark results [skip ci]'
          default_author: github_actions
