name: Build
on:
  schedule:
    - cron: "45 0 * * *" # Run at 00:45 every day
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@v0.2.27
        with:
          cuda: '13.0.0'
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build for production
        env:
          LD_LIBRARY_PATH: "${{ env.CUDA_PATH }}/lib64:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
        run: cargo build --release
