name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run linter
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check code format
        run: cargo fmt -- --check
