name: Lint
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@v0.2.27
        with:
          cuda: '13.0.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart", "cudart-dev", "thrust"]'

      - name: Install nvidia-smi
        run: |
          # Install nvidia-smi utility without full driver stack
          # Using nvidia-utils package which provides just the tools
          sudo apt-get update
          sudo apt-get install -y nvidia-utils-535 nvidia-settings

          # Add nvidia-smi to PATH and verify it works
          export PATH="/usr/bin:/usr/local/cuda/bin:$PATH"
          which nvidia-smi || echo "nvidia-smi not found"

          # Create a mock nvidia-smi if the real one doesn't work (fallback)
          if ! command -v nvidia-smi &> /dev/null; then
            echo "Creating mock nvidia-smi"
            sudo tee /usr/local/bin/nvidia-smi > /dev/null << 'EOF'
          #!/bin/bash
          if [[ "$1" == "--query-gpu=compute_cap" && "$2" == "--format=csv" ]]; then
            echo "compute_cap"
            echo "8.0"
          else
            echo "NVIDIA-SMI 535.86.10   Driver Version: 535.86.10   CUDA Version: 13.0"
            echo ""
            echo "GPU 0: Mock GPU (UUID: GPU-12345678)"
          fi
          EOF
            sudo chmod +x /usr/local/bin/nvidia-smi
          fi

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Update dependencies for CUDA 13.0 support
        run: |
          echo "Updating dependencies to ensure cudarc 0.17.3+ for CUDA 13.0 support..."
          cargo update
      - name: Run linter
        env:
          LD_LIBRARY_PATH: "${{ env.CUDA_PATH }}/lib64:/usr/lib/x86_64-linux-gnu:${{ env.LD_LIBRARY_PATH }}"
        run: cargo lint

      - name: Check code format
        run: cargo fmt -- --check

      - name: Install cargo-machete
        run: cargo install cargo-machete

      - name: Check for unused dependencies
        run: cargo machete
