name: Lint
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@v0.2.27
        with:
          cuda: '13.0.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart", "cudart-dev", "thrust"]'

      - name: Install NVIDIA drivers for nvidia-smi
        run: |
          # Add NVIDIA package repositories
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update

          # Install nvidia-smi (r580+ compatible with CUDA 13.0)
          sudo apt-get install -y nvidia-utils-580
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Update dependencies for CUDA 13.0 support
        run: |
          echo "Updating dependencies to ensure cudarc 0.17.3+ for CUDA 13.0 support..."
          cargo update
      - name: Run linter
        env:
          LD_LIBRARY_PATH: "${{ env.CUDA_PATH }}/lib64:/usr/lib/x86_64-linux-gnu:${{ env.LD_LIBRARY_PATH }}"
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check code format
        run: cargo fmt -- --check

      - name: Install cargo-machete
        run: cargo install cargo-machete

      - name: Check for unused dependencies
        run: cargo machete
